jacobota/CookBooked

.gitignore
server/package.json

* Added script command "start" to start the node server.
* Added coverage report for jest.
* Enabled clearing of mocks after every test for jest unit tests.
* Ignored test coverage folder in gitignore.

chore: improve package.json

---

server/__test__/WebToken.test.js
server/package-lock.json
server/package.json
server/src/util/WebToken.js

added jsonwebtoken to util, as well as functions to generate a token, authenticate a token (router middleware), and validate admin access. functions will need more thorough testing (incl. API testing) once merged with version containing account creation and login functionality

feature-jsonwebtoken impl.

---

server/__test__/service/PostReview.test.js
server/app.js
server/package-lock.json
server/package.json
server/src/controller/ReviewsRouter.js
server/src/repository/ReviewsDAO.js
server/src/service/ReviewsService.js
server/src/util/ReviewsHelper.js

Added the feature for posting a new review to the DB

Added new review feature

---

server/__test__/repository/ReviewsDAOHelpers.test.js
server/src/repository/ReviewsDAO.js
server/src/repository/ReviewsDAOHelpers.js

The commit for the style makes no functional changes.  It is only visual changes for displaying the code, made by the Prettier extension.
The DAO implementation is only for getting reviews by recipe ID.

feat: implement DAO for getting reviews by recipe

---

server/__test__/service/ReviewsService.test.js
server/src/errors/ArgumentError.js
server/src/errors/CookBookedError.js
server/src/service/ReviewsService.js

* Added getReviews function in ReviewService.js, which will handle any given valid parameters for retrieving reviews, and then call the appropriate DAO function.
* In ReviewService.js, Prettier made stylistic changes to the top half of the file .

feat: implement Service for getting reviews by recipe

---

server/__test__/service/AccountsService.test.js
server/src/controller/AccountsRouter.js
server/src/repository/AccountsDAO.js
server/src/service/AccountsService.js

added feature allowing users to update their aboutMe and imageUrl attributes in accounts db. unit tested service layer function.

feature: update profile info

---

server/__test__/repository/ReviewsDAOHelpers.test.js
server/src/repository/ReviewsDAOHelpers.js

The code related to environment variables was from an earlier state of development, when the final environment variable configuration was not set.  It has now been updated with the correct variable names and path.

fix: update environment variables

---

server/__test__/service/AccountsService.test.js
server/src/controller/AccountsRouter.js
server/src/repository/AccountsDAO.js
server/src/repository/ReviewsDAO.js
server/src/service/AccountsService.js
server/src/util/WebToken.js

removed extra querycommand import from reviewsdao, removed redundant validatefields function from accountsservice and associated tests, fixed bug that caused server to crash when registration was attempted without a password in req body, removed secretkey export from webtoken.js, added logger statements to significant functions

bug fix: 03/09 2:46

---

server/__test__/controller/ReviewsRouterHelpers.test.js
server/src/controller/ReviewsRouterHelpers.js
server/src/repository/ReviewsDAO.js
server/src/service/ReviewsService.js

This completes the controller portion of the feature.

Implement router for get reviews by author

---

server/__test__/service/ReviewsService.test.js

Details in individual commits.

Fix and refactor ReviewsService.test.js

---

server/__test__/service/DeleteReview.test.js
server/src/controller/ReviewsRouter.js
server/src/repository/ReviewsDAO.js
server/src/service/ReviewsService.js

Added Admin and only own User deletion priviledges to deleteReview

---

server/__test__/service/ReviewsService.test.js

Moved tests around and added extra "describe" functions for easier readability.  No core code has been changed, even though Git's displayed changes appears otherwise.

style: organize ReviewsService.test.js

---

server/__test__/service/PostReview.test.js
server/src/service/ReviewsService.js

This will allow a GSI that can be queried for recent reviews.

feat: add isRecent attribute to new reviews

---

client/package-lock.json
client/package.json
client/public/index.html
client/src/Components/BrowseRecipes/BrowseRecipes.tsx
client/src/Components/Util/DropDown.css
client/src/Components/Util/DropDown.tsx

- Created filter, grabbed categories from TheMealDB and connected them to the filter through state
- Set up for grabbing recipes by those categories

Added dropdown menu and got elements from TheMealDB

---

server/__test__/controller/ReviewsRouterHelpers.test.js
server/__test__/repository/ReviewsDAOHelpers.test.js
server/__test__/service/ReviewsService.test.js
server/src/controller/ReviewsRouterHelpers.js
server/src/repository/ReviewsDAO.js
server/src/repository/ReviewsDAOHelpers.js
server/src/service/ReviewsService.js

Details in individual commits.

Feat: implement getting recent reviews

---

server/__test__/service/ReviewsService.test.js
server/src/service/ReviewsService.js

* Changed the Limit property amount used for retrieving reviews from DynamoDB from 100 to 50, since 50 is more reasonable.

fix: update max number of reviews retrieved

---

client/src/types/types.ts

* Added the new attribute "recipeName" to the Review interface, in relation to the new attribute to the database table.

feat: update types

---

client/src/Components/ReviewCard/ReviewCard.css
client/src/Components/ReviewCard/ReviewCardController.tsx
client/src/Components/ReviewCard/ReviewCardView.tsx

Creates the review component that can be used to display a card of a review amongst other reviews, or display the full review on a review's webpage.

feat: create review card

---

client/src/Components/CommentCard/CommentCard.css
client/src/Components/CommentCard/CommentCardController.tsx
client/src/Components/CommentCard/CommentCardView.tsx

This adds the HTML & JavaScript portion of the comment card.

feat: create comment card

---

client/src/Components/ReviewCard/ReviewCard.css
client/src/Components/ReviewCard/ReviewCardView.tsx

feat: style review card

---

client/src/Components/CommentCard/CommentCard.css
client/src/Components/CommentCard/CommentCardView.tsx

feat: style comment card

---

client/src/Components/Review/ReviewPage.css
client/src/Components/Review/ReviewPageView.tsx

feat: style review page
